[[plugins]]
repo = 'mattn/vim-sl'
hook_add = '''
    command! SL call sl#animate()
'''

[[plugins]]
repo = 'mattn/calendar-vim'
on_cmd = [ 'Calendar', 'CalendarT', 'CalendarH']

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-skk/skkeleton'
depends = 'denops.vim'
on_map = {ic = '<Plug>(skkeleton-toggle)'}
hook_add = '''
    imap <C-j> <Plug>(skkeleton-toggle)
    cmap <C-j> <Plug>(skkeleton-toggle)
'''
hook_source = '''
    source ~/dotfiles/.vim/plugins/skkeleton.vim
'''
